name: public build

on:
  workflow_dispatch:

jobs:

  build_linux:
    runs-on: ubuntu-22.04
    steps:
      - run: ./build/build_linux.sh ci

  build_macos:
    runs-on: macos-13
    steps:
      - run: ./build/build_macos.sh ci
