name: website update

on:
  workflow_dispatch:

jobs:
  web_update:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        cd doc
        pip3 install -r requirements.txt
        cd OSL
        python3 make_osl_document.py
        cd ..
        python3 docgen.py
        cd ..
        wget -O - https://github.com/cobalt-org/cobalt.rs/releases/download/v0.19.2/cobalt-v0.19.2-x86_64-unknown-linux-gnu.tar.gz|tar -xzf - ./cobalt
        cd web
        ../cobalt build
        cd _site
        tar -czf ../../_site.tar.gz *
        cd ../..
        curl -u "${{secrets.CIFTP}}" -s -T _site.tar.gz ftp://nvgt.gg/_site.tar.gz

